#!/usr/bin/env python3
"""15s rank-1 proof: only the newly appended word pops; old transcript remains still."""
import json
import re
from pathlib import Path

from shared.pipeline import CropAnalysis, build_subtitle_ass, render_vertical_clip

JOB = "9f8d3aa64a3f4cf28546c4c4d2ba2797"
START = 3062.599
DURATION = 15.0
HOOK = "Tes Masuk Hedge Fund: 99% Orang Gagal Jawab Pertanyaan Koin Ini"
base = Path("/data/work") / JOB
source = next(base.glob("*.mkv"))
raw_segments = json.loads((base / "transcript.json").read_text(encoding="utf-8"))["segments"]
# YouTube emitted overlapping 50ms micro-segments here. Combine the selected
# native words into one deterministic 15s stream so each new-word pop is visible.
selected_words: list[str] = []
for item in raw_segments:
    if float(item["end"]) <= START or float(item["start"]) >= START + DURATION:
        continue
    selected_words.extend(str(item.get("text", "")).split())
segments = [{
    "start": START,
    "end": START + DURATION,
    "text": " ".join(selected_words),
    "words": [],
}]
out = Path("/data/videos") / f"{JOB}.active-new-word-only-15s.mp4"
ass = out.with_suffix(".ass")

build_subtitle_ass(segments, START, START + DURATION, ass, "1080x1920", HOOK, "aura")
text = ass.read_text(encoding="utf-8")
lines: list[str] = []
# Captions generated by continuous mode have each token formatted as {\1c&H...}WORD.
token_re = re.compile(r"(\{\\1c&H[0-9A-F]{8}\})([^{}\\]+)")
for line in text.splitlines():
    if not line.startswith("Dialogue: 1,"):
        lines.append(line)
        continue
    # Remove block-level scale transitions: old words must not move.
    line = re.sub(r"\\t\(0,120,\\fscx105\\fscy105\)\\t\(120,220,\\fscx100\\fscy100\)", "", line)
    matches = list(token_re.finditer(line))
    if not matches:
        lines.append(line)
        continue
    last = matches[-1]
    # Only final / freshly appended word is enlarged briefly and settles in 150ms.
    replacement = last.group(1) + r"{\fscx128\fscy128\t(0,150,\fscx100\fscy100)}" + last.group(2)
    line = line[:last.start()] + replacement + line[last.end():]
    lines.append(line)
ass.write_text("\n".join(lines) + "\n", encoding="utf-8")

crop = CropAnalysis(
    crop_x=1240, crop_y=0, crop_w=1080, crop_h=1920,
    face_hits=44, scene_cuts=3, samples=45,
    mode="face-stabilized", reason="Reuse verified rank-1 crop",
    aspect_ratio="9:16", two_person_frames=0,
)
render_vertical_clip(source, out, START, DURATION, "1080x1920", 30, ass, crop)
print(json.dumps({"output": str(out), "ass": str(ass), "duration": DURATION, "animation": "new word only"}))
